iou_thresholds: [0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,0.55, 0.6]

geometry_mode: '3d'

camera_position: [-9.91, 4.97, 0.5]
camera_rotation: [ [1.0000000000000002, 6.661338147750939e-16, 2.220446049250313e-16], [-4.4408920985006257e-16, -2.220446049250314e-16, 1.0000000000000002], [4.440892098500626e-16, -1.0000000000000002, -4.440892098500626e-16] ]

evaluation_data: [
  {
    name_id: 'SingleLargeForkliftC-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/dynamic_no_occlusion/SingleLargeForkliftC-v1-t1-det1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleLargeForkliftC-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 7,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleLargeForkliftC-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/dynamic_no_occlusion/SingleLargeForkliftC-v1-t1-det1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleLargeForkliftC-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 7,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleLargeForkliftB-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/dynamic_no_occlusion/SingleLargeForkliftB-v1-t1-det1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleLargeForkliftB-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 7,
    synthetic_fps: 30,
  },
]

