euclidean_distance_thresholds: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1., 1.5, 2.]

geometry_mode: '3d'

camera_position: [-9.91, 4.97, 0.5]
camera_rotation: [ [1.0000000000000002, 6.661338147750939e-16, 2.220446049250313e-16], [-4.4408920985006257e-16, -2.220446049250314e-16, 1.0000000000000002], [4.440892098500626e-16, -1.0000000000000002, -4.440892098500626e-16] ]

results_recording:
  enabled: True
  output_dir: 'detection_evaluation/results/temp_ap_comp/multi_eucdist_3ddet-ermis_det_3-dynamic_no_occlusion-all-t1'

evaluation_data: [
  {
    name_id: 'MultiMediumBots-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/MultiMediumBots-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiMediumBots-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 7,
    synthetic_fps: 30,
  },
  {
    name_id: 'MultiMediumLargeBots-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/MultiMediumLargeBots-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiMediumLargeBots-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'MultiMediumSmallBots-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/MultiMediumSmallBots-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiMediumSmallBots-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'MultiMixed-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/MultiMixed-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiMixed-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'MultiPeople-v1-t2',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/MultiPeople-v1-t2-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiPeople-v1-t2',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'MultiPeople-v2-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/MultiPeople-v2-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiPeople-v2-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'MultiSmallBots-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/MultiSmallBots-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiSmallBots-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleLargeForkliftB-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SingleLargeForkliftB-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleLargeForkliftB-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 7,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleLargeForkliftC-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SingleLargeForkliftC-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleLargeForkliftC-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 7,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleMediumCarter-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SingleMediumCarter-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleMediumCarter-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleMediumJackal-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SingleMediumJackal-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleMediumJackal-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleMediumJackal-v1-t2',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SingleMediumJackal-v1-t2-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleMediumJackal-v1-t2',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleMediumTransporter-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SingleMediumTransporter-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleMediumTransporter-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SinglePerson-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SinglePerson-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SinglePerson-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SinglePerson-v2-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SinglePerson-v2-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SinglePerson-v2-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SinglePerson-v3-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SinglePerson-v3-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SinglePerson-v3-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  #{
  #  name_id: 'SinglePerson-v4-t1',
  #  detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SinglePerson-v4-t1-erm3',
  #  synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SinglePerson-v4-t1',
  #  detection_frame_offset: 0,
  #  synthetic_frame_offset: 6,
  #  synthetic_fps: 30,
  #},
  {
    name_id: 'SingleSmallJetbot-v1-t5',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SingleSmallJetbot-v1-t5-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleSmallJetbot-v1-t5',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SingleSmallKaya-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ermis_detection/ermis_v3/dynamic_no_occlusion/SingleSmallKaya-v1-t1-erm3',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SingleSmallKaya-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  }
]

