detection_loader:
  #data_path: '/home/digi2/colino_dir/detection_data/ermis_detection/detection_res_2' # Path to the detection data on the RTX machine
  data_path: '/home/colino/hawk/detection_data/ermis_detection/detection_res_2' # Path to the detection data on the Personal machine
  int_precision: 5

synthetic_loader:
  #data_path: '/home/digi2/colino_dir/gen_data_ground_truth/figure8_transporter_empty-30fps_800frames-rec1' # Path to the synthetic data on the RTX machine
  data_path: '/home/colino/hawk/synthetic_ground_truth/figure8_transporter_empty-30fps_200frames-rec1' # Path to the synthetic data on the Personal machine
  int_precision: 4
  single_sem_classes: ['transporter1_mesh']
  camera_position: [-10.000000000540384, 5.0018717613276635, 0.21277073854091316]
  camera_rotation: [
        [0.9999999999999993, 3.42285420007471e-8, 0],
        [-5.434188106286747e-22, 1.587618925213973e-14, 1],
        [3.42285420007471e-8, -0.9999999999999993, 1.587618925213974e-14]
    ]

alignment_config:
  detection_frame_offset: 0
  synthetic_frame_offset: 0
  synthetic_fps: 30
  playback_speed: 2.0 # 1.0 for real-time playback, used for better visualization
