euclidean_distance_thresholds: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1., 1.5, 2.]

geometry_mode: '3d'

camera_position: [-9.91, 4.97, 0.5]
camera_rotation: [ [1.0000000000000002, 6.661338147750939e-16, 2.220446049250313e-16], [-4.4408920985006257e-16, -2.220446049250314e-16, 1.0000000000000002], [4.440892098500626e-16, -1.0000000000000002, -4.440892098500626e-16] ]

results_recording:
  enabled: True
  output_dir: 'detection_evaluation/results/people_fusion_comparison/multi_eucdist-ganelis_det_1-dynamic_no_occlusion-people_only-t1'

evaluation_data: [
  {
    name_id: 'MultiMixed-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ganelis_detection/dynamic_no_occlusion/MultiMixed-v1-t1-gan1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiMixed-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'MultiPeople-v1-t2',
    detection_path: '/home/colino/hawk/detection_data/ganelis_detection/dynamic_no_occlusion/MultiPeople-v1-t2-gan1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiPeople-v1-t2',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'MultiPeople-v2-t1',
    detection_path: '/home/colino/hawk/detection_data/ganelis_detection/dynamic_no_occlusion/MultiPeople-v2-t1-gan1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/MultiPeople-v2-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SinglePerson-v1-t1',
    detection_path: '/home/colino/hawk/detection_data/ganelis_detection/dynamic_no_occlusion/SinglePerson-v1-t1-gan1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SinglePerson-v1-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SinglePerson-v2-t1',
    detection_path: '/home/colino/hawk/detection_data/ganelis_detection/dynamic_no_occlusion/SinglePerson-v2-t1-gan1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SinglePerson-v2-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  },
  {
    name_id: 'SinglePerson-v3-t1',
    detection_path: '/home/colino/hawk/detection_data/ganelis_detection/dynamic_no_occlusion/SinglePerson-v3-t1-gan1',
    synthetic_path: '/home/colino/hawk/synthetic_ground_truth/dynamic_no_occlusion/SinglePerson-v3-t1',
    detection_frame_offset: 0,
    synthetic_frame_offset: 6,
    synthetic_fps: 30,
  }
]

